#! /bin/sh


sxhkd -m -1 &
picom &
feh --bg-scale $HOME/Pictures/wallpaper/randall-mackey-mural2.jpg
$HOME/.config/polybar/launch.sh &
setxkbmap -model pc104 -layout us -variant colemak
fcitx5 & 
redshift &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

# bspc config focused_border_color  "#ff79c6"
# bspc config active_border_color   "#bd93f9"
# bspc config presel_feedback_color "#6272a4"
bspc config normal_border_color   "#44475a"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
